In [1]:
from tabula import read_pdf

In [2]:
from tabulate import tabulate

In [4]:
import PyPDF2 as pdf
import re

# Aurobinda Pharma for 2017-18

In [3]:
import PyPDF2 as pdf
import re

# open the pdf file
object = pdf.PdfFileReader("Annual-Report-2017-18.pdf")

# get number of pages
NumPages = object.getNumPages()

# define keyterms
String = "CONSOLIDATED BALANCE SHEET"
String1 = "STANDALONE STATEMENT OF PROFIT AND LOSS"
String2 = "STANDALONE STATEMENT OF CASH FLOW"
# extract text and do the search
for i in range(0, NumPages):
    PageObj = object.getPage(i)
    Text = PageObj.extractText() 
    # print(Text)
    if  re.search(String, Text) != None:
        print("This is page " + str(i))
        page=object.getPage(i)
        pdf_writer=pdf.PdfFileWriter()
        pdf_writer.addPage(page)
        output=open('balancesheet_aurobindo_1718.pdf','wb')
        pdf_writer.write(output)
        output.close()
        df=read_pdf('balancesheet_aurobindo_1718.pdf')
df[0]
# for i in range(0, NumPages):
#     PageObj = object.getPage(i)
#     Text = PageObj.extractText() 
#     # print(Text)
#     if  re.search(String1, Text) != None:
#         print("This is page " + str(i))
#         page=object.getPage(i)
#         pdf_writer=pdf.PdfFileWriter()
#         pdf_writer.addPage(page)
#         output=open('p&l.pdf','wb')
#         pdf_writer.write(output)
#         output.close()
        
# for i in range(0, NumPages):
#     PageObj = object.getPage(i)
#     Text = PageObj.extractText() 
#     # print(Text)
#     if  re.search(String2, Text) != None:
#         print("This is page " + str(i))
#         page=object.getPage(i)
#         pdf_writer=pdf.PdfFileWriter()
#         pdf_writer.addPage(page)
#         output=open('cashflow.pdf','wb')
#         pdf_writer.write(output)
#         output.close()

This is page 205

'pages' argument isn't specified.Will extract only from page 1 by default.

,Unnamed: 0,Unnamed: 1,Unnamed: 2,As at,As at.1
0,NaN,NaN,Notes,31 March 2018,31 March 2017
1,I,ASSETS,NaN,NaN,NaN
2,NaN,Non-current assets,NaN,NaN,NaN
3,NaN,"(a) Property, plant and equipment",3,"47,365.6","40,830.5"
4,NaN,(b) Capital work-in-progress,3,"13,995.4","12,373.6"
5,NaN,(c) Goodwill,4,"8,165.5","4,063.0"
6,NaN,(d) Other intangible assets,5,"9,675.7","3,444.3"
7,NaN,(e) Intangible assets under development,5,"1,835.0","2,207.2"
8,NaN,(f) Financial assets,NaN,NaN,NaN
9,NaN,(i) Investments,6(A),"3,115.2","2,458.5"
10,NaN,(ii) Trade receivables,7(A),-,-
11,NaN,(iii) Loans,8(A),54.4,57.0
12,NaN,(iv) Other financial assets,9(A),874.6,751.7
13,NaN,(g) Deferred tax assets (net),10(A),"1,588.0","1,677.6"
14,NaN,(h) Non-current tax assets (net),11(A),825.9,579.8
15,NaN,(i) Other non-current assets,12(A),"1,678.3","1,989.2"
16,NaN,Total non-current assets,NaN,"89,173.6","70,432.4"
17,NaN,Current assets,NaN,NaN,NaN
18,NaN,(a) Inventories,13,"58,584.1","43,305.4"
19,NaN,(b) Financial assets,NaN,NaN,NaN
20,NaN,(i) Investments,6(B),0.2,0.2
21,NaN,(ii) Trade receivables,7(B),"30,843.6","27,653.3"
22,NaN,(iii) Cash and cash equivalents,14(A),"12,159.0","4,894.4"
23,NaN,(iv) Bank balances other than (iii) above,14(B),457.2,240.4
24,NaN,(v) Loans,8(B),101.9,108.9
25,NaN,(vi) Other financial assets,9(B),"7,942.0","7,576.5"
26,NaN,(c) Current tax assets (net),11(B),645.5,175.1
27,NaN,(d) Other current assets,12(B),"11,144.9","8,107.6"
28,NaN,Total current assets,NaN,"121,878.4","92,061.8"
29,NaN,TOTAL ASSETS,NaN,"211,052.0","162,494.2"
30,II.,EQUITY AND LIABILITIES,NaN,NaN,NaN
31,NaN,Equity,NaN,NaN,NaN
32,NaN,(a) Equity share capital,15,585.9,585.9
33,NaN,(b) Other equity,16,"116,218.3","93,133.2"
34,NaN,Equity attributable to equity holders of Paren...,NaN,"116,804.2","93,719.1"
35,NaN,(c) Non-controlling interest,NaN,18.2,20.8
36,NaN,Total equity,NaN,"116,822.4","93,739.9"
37,NaN,Liabilities,NaN,NaN,NaN
38,NaN,Non-current liabilities,NaN,NaN,NaN
39,NaN,(a) Financial liabilities,NaN,NaN,NaN
40,NaN,(i) Borrowings,17(A),"4,512.0","1,814.0"
41,NaN,(b) Provisions,18(A),558.6,391.3
42,NaN,(c) Deferred tax liabilities (net),10(B),"2,352.8",493.0
43,NaN,Total non-current liabilities,NaN,"7,423.4","2,698.3"
44,NaN,Current liabilities,NaN,NaN,NaN
45,NaN,(a) Financial liabilities,NaN,NaN,NaN
46,NaN,(i) Borrowings,17(B),"40,313.4","29,027.2"
47,NaN,(ii) Trade payables,19,"26,274.4","21,547.0"
48,NaN,(iii) Other financial liabilities,20,"5,100.0","4,693.8"
49,NaN,(b) Other current liabilities,21,"12,678.0","8,174.4"
50,NaN,(c) Provisions,18(B),"2,009.3","2,349.0"
51,NaN,(d) Current tax liabilities (net),22,431.1,264.6
52,NaN,Total current liabilities,NaN,"86,806.2","66,056.0"
53,NaN,TOTAL EQUITY AND LIABILITIES,NaN,"211,052.0","162,494.2"
54,NaN,Summary of significant accounting policies,2.3,NaN,NaN

In [4]:
print(tabulate(df[0]))

--  ---  -------------------------------------------------------  -----  -------------  -------------
 0  nan  nan                                                      Notes  31 March 2018  31 March 2017
 1  I    ASSETS                                                   nan    nan            nan
 2  nan  Non-current assets                                       nan    nan            nan
 3  nan  (a)  Property, plant and equipment                       3      47,365.6       40,830.5
 4  nan  (b)  Capital work-in-progress                            3      13,995.4       12,373.6
 5  nan  (c)  Goodwill                                            4      8,165.5        4,063.0
 6  nan  (d)  Other intangible assets                             5      9,675.7        3,444.3
 7  nan  (e)  Intangible assets under development                 5      1,835.0        2,207.2
 8  nan  (f)  Financial assets                                    nan    nan            nan
 9  nan  (i) Investments                                          6(A)   3,115.2        2,458.5
10  nan  (ii) Trade receivables                                   7(A)   -              -
11  nan  (iii) Loans                                              8(A)   54.4           57.0
12  nan  (iv) Other financial assets                              9(A)   874.6          751.7
13  nan  (g)  Deferred tax assets (net)                           10(A)  1,588.0        1,677.6
14  nan  (h)  Non-current tax assets (net)                        11(A)  825.9          579.8
15  nan  (i)  Other non-current assets                            12(A)  1,678.3        1,989.2
16  nan  Total non-current assets                                 nan    89,173.6       70,432.4
17  nan  Current assets                                           nan    nan            nan
18  nan  (a)  Inventories                                         13     58,584.1       43,305.4
19  nan  (b)  Financial assets                                    nan    nan            nan
20  nan  (i)  Investments                                         6(B)   0.2            0.2
21  nan  (ii)  Trade receivables                                  7(B)   30,843.6       27,653.3
22  nan  (iii)  Cash and cash equivalents                         14(A)  12,159.0       4,894.4
23  nan  (iv)  Bank balances other than (iii) above               14(B)  457.2          240.4
24  nan  (v)  Loans                                               8(B)   101.9          108.9
25  nan  (vi)  Other financial assets                             9(B)   7,942.0        7,576.5
26  nan  (c)  Current tax assets (net)                            11(B)  645.5          175.1
27  nan  (d)  Other current assets                                12(B)  11,144.9       8,107.6
28  nan  Total current assets                                     nan    121,878.4      92,061.8
29  nan  TOTAL ASSETS                                             nan    211,052.0      162,494.2
30  II.  EQUITY AND LIABILITIES                                   nan    nan            nan
31  nan  Equity                                                   nan    nan            nan
32  nan  (a)  Equity share capital                                15     585.9          585.9
33  nan  (b)  Other equity                                        16     116,218.3      93,133.2
34  nan  Equity attributable to equity holders of Parent company  nan    116,804.2      93,719.1
35  nan  (c)  Non-controlling interest                            nan    18.2           20.8
36  nan  Total equity                                             nan    116,822.4      93,739.9
37  nan  Liabilities                                              nan    nan            nan
38  nan  Non-current liabilities                                  nan    nan            nan
39  nan  (a)  Financial liabilities                               nan    nan            nan
40  nan  (i)  Borrowings                                          17(A)  4,512.0        1,814.0
41  nan  (b)  Provisions                                          18(A)  558.6          391.3
42  nan  (c)  Deferred tax liabilities (net)                      10(B)  2,352.8        493.0
43  nan  Total non-current liabilities                            nan    7,423.4        2,698.3
44  nan  Current liabilities                                      nan    nan            nan
45  nan  (a)  Financial liabilities                               nan    nan            nan
46  nan  (i)  Borrowings                                          17(B)  40,313.4       29,027.2
47  nan  (ii)  Trade payables                                     19     26,274.4       21,547.0
48  nan  (iii)  Other financial liabilities                       20     5,100.0        4,693.8
49  nan  (b)  Other current liabilities                           21     12,678.0       8,174.4
50  nan  (c) Provisions                                           18(B)  2,009.3        2,349.0
51  nan  (d)  Current tax liabilities (net)                       22     431.1          264.6
52  nan  Total current liabilities                                nan    86,806.2       66,056.0
53  nan  TOTAL EQUITY AND LIABILITIES                             nan    211,052.0      162,494.2
54  nan  Summary of significant accounting policies               2.3    nan            nan
--  ---  -------------------------------------------------------  -----  -------------  -------------

In [20]:
# open the pdf file
object = pdf.PdfFileReader("Annual-Report-2017-18.pdf")

# get number of pages
NumPages = object.getNumPages()

String1 = "STANDALONE STATEMENT OF PROFIT AND LOSS"

for i in range(0, NumPages):
    PageObj = object.getPage(i)
    Text = PageObj.extractText() 
    # print(Text)
    if  re.search(String1, Text) != None:
        print("This is page " + str(i))
        page=object.getPage(i)
        pdf_writer=pdf.PdfFileWriter()
        pdf_writer.addPage(page)
        output=open('p&l_aurobindo_1718.pdf','wb')
        pdf_writer.write(output)
        output.close()
        df_pl=read_pdf('p&l_aurobindo_1718.pdf')
print(tabulate(df_pl[0]))

'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 144
--  ----  --------------------------------------------------------------------------------  ----  -------------  -------------
 0  nan   nan                                                                               Note  31 March 2018  31 March 2017
 1  I     INCOME                                                                            nan   nan            nan
 2  nan   Revenue from operations                                                           20    103,031.5      97,812.1
 3  nan   Other income                                                                      21    806.5          1,359.5
 4  nan   TOTAL INCOME (I)                                                                  nan   103,838.0      99,171.6
 5  II    EXPENSES                                                                          nan   nan            nan
 6  nan   Cost of materials consumed                                                        22    48,932.7       46,041.9
 7  nan   Purchases of stock-in-trade                                                       nan   37.2           112.1
 8  nan   Changes in inventories of  finished goods, stock-in-trade and work-in-progress    23    (3,341.8)      313.2
 9  nan   Employee benefits expense                                                         24    11,316.4       9,273.0
10  nan   Finance costs                                                                     25    528.9          451.6
11  nan   Depreciation expense                                                              26    3,548.3        2,861.7
12  nan   Other expenses                                                                    27    19,386.9       18,332.4
13  nan   TOTAL EXPENSES (II)                                                               nan   80,408.6       77,385.9
14  III   PROFIT BEFORE TAX (I-II)                                                          nan   23,429.4       21,785.7
15  IV    TAX EXPENSE :                                                                     28    nan            nan
16  nan   Current tax                                                                       nan   5,053.4        4,620.6
17  nan   Tax credit - Minimum Alternate Tax (MAT)                                          nan   (433.2)        (642.8)
18  nan   Deferred tax                                                                      nan   681.5          740.3
19  nan   TOTAL TAX EXPENSE (IV)                                                            nan   5,301.7        4,718.1
20  V     PROFIT FOR THE YEAR (III-IV)                                                      nan   18,127.7       17,067.6
21  VI    OTHER COMPREHENSIVE INCOME (OCI)                                                  nan   nan            nan
22  nan   Items that will not to be reclassified subsequently to profit or loss:            nan   nan            nan
23  nan   (a) Re-measurement of defined benefit liability                                   nan   (34.5)         (85.7)
24  nan   (b) Income-tax relating to items that will not be reclassified to profit or loss  nan   12.7           29.7
25  nan   TOTAL OTHER COMPREHENSIVE INCOME FOR THE YEAR (NET OF TAX) (VI)                   nan   (21.8)         (56.1)
26  VII   TOTAL COMPREHENSIVE INCOME FOR THE YEAR (NET OF TAX) (V+VI)                       nan   18,105.9       17,011.5
27  VIII  EARNINGS PER EQUITY SHARE                                                         29    nan            nan
28  nan   Basic (in `)                                                                      nan   30.94          29.16
29  nan   Diluted (in `)                                                                    nan   30.94          29.16
30  nan   Nominal value per equity share                                                    nan   1.00           1.00
31  nan   Summary of significant accounting policies                                        2.2   nan            nan
--  ----  --------------------------------------------------------------------------------  ----  -------------  -------------

In [28]:
# open the pdf file
object = pdf.PdfFileReader("Annual-Report-2017-18.pdf")

# get number of pages
NumPages = object.getNumPages()
String2 = "STANDALONE STATEMENT OF CASH FLOW"
pdf_writer=pdf.PdfFileWriter()
for i in range(0, NumPages):
    PageObj = object.getPage(i)
    Text = PageObj.extractText() 
    # print(Text)
    if  re.search(String2, Text) != None:
        print("This is page " + str(i))
        page=object.getPage(i)
        pdf_writer.addPage(page)
output=open('cashflow.pdf','wb')
pdf_writer.write(output)
output.close()
df_cash=read_pdf('cashflow.pdf',pages='all')

This is page 146
This is page 147

In [27]:
df_cash

In [18]:
import camelot
tables=camelot.read_pdf("cashflow.pdf")

In [19]:
tables

In [25]:
# # open the pdf file
# object = pdf.PdfFileReader("Annual-Report-2016-17.pdf")
# # get number of pages
# NumPages = object.getNumPages()



# String2 = "STANDALONE STATEMENT OF CASH FLOW"




# for i in range(0, NumPages):
#     PageObj = object.getPage(i)
#     Text = PageObj.extractText() 
#     # print(Text)
#     pdf_writer=pdf.PdfFileWriter()
#     if  re.search(String2, Text) != None:
#         print("This is page " + str(i))
#         page=object.getPage(i)
#         pdf_writer=pdf.PdfFileWriter()
#         pdf_writer.addPage(page)
#         output=open('cashflow17181old.pdf','wb')
#         pdf_writer.write(output)
#     output.close()

# Aurobindo Pharma for 2018-2019

## Balance Sheet

In [14]:

# open the pdf file
object = pdf.PdfFileReader("APL-Annual-Report-2018-19.pdf")

# get number of pages
NumPages = object.getNumPages()

# define keyterms
String = "STANDALONE BALANCE SHEET"
# String1 = "STANDALONE STATEMENT OF PROFIT AND LOSS"
# String2 = "STANDALONE STATEMENT OF CASH FLOW"
# extract text and do the search
for i in range(0, NumPages):
    PageObj = object.getPage(i)
    Text = PageObj.extractText() 
    # print(Text)
    if  re.search(String, Text) != None:
        print("This is page " + str(i))
        page=object.getPage(i)
        pdf_writer=pdf.PdfFileWriter()
        pdf_writer.addPage(page)
        output=open('balancesheet_aurobindo1819.pdf','wb')
        pdf_writer.write(output)
        output.close()
        df_bl1819=read_pdf('balancesheet_aurobindo1819.pdf')
df_bl1819[0]

'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 143

,Unnamed: 0,Unnamed: 1,Unnamed: 2,As at,As at.1
0,NaN,NaN,Note,NaN,NaN
1,NaN,NaN,NaN,31 March 2019,31 March 2018
2,I,ASSETS,NaN,NaN,NaN
3,NaN,Non-current assets,NaN,NaN,NaN
4,NaN,"(a) Property, plant and equipment",3(A),"41,458.5","33,929.7"
5,NaN,(b) Capital work-in-progress,3(A),"7,500.7","11,002.3"
6,NaN,(c) Intangible assets,3(B),38.5,-
7,NaN,(d) Intangible assets under development,3(B),389.4,437.5
8,NaN,(e) Financial assets,NaN,NaN,NaN
9,NaN,(i) Investments,4(A),"23,390.4","19,674.8"
10,NaN,(ii) Loans,5,"1,465.6",132.6
11,NaN,(iii) Trade receivables,6(A),-,-
12,NaN,(iv) Other financial assets,7(A),982.7,964.1
13,NaN,(f) Non-current tax assets (net),9,"1,381.1",826.0
14,NaN,(g) Other non-current assets,10(A),716.9,"1,159.4"
15,NaN,Total non-current assets,NaN,"77,323.8","68,126.4"
16,NaN,Current assets,NaN,NaN,NaN
17,NaN,(a) Inventories,11,"39,712.6","34,092.3"
18,NaN,(b) Financial assets,NaN,NaN,NaN
19,NaN,(i) Investments,4(B),0.2,0.2
20,NaN,(ii) Trade receivables,6(B),"52,320.7","44,682.3"
21,NaN,(iii) Cash and cash equivalents,12(A),734.0,"2,440.0"
22,NaN,(iv) Bank balances other than (iii) above,12(B),23.7,19.0
23,NaN,(v) Loans,5(B),98.2,82.3
24,NaN,(vi) Other financial assets,7(B),202.5,81.4
25,NaN,(c) Other current assets,10(B),"10,991.5","8,414.5"
26,NaN,Total current assets,NaN,"104,083.4","89,812.0"
27,NaN,TOTAL ASSETS,NaN,"181,407.2","157,938.4"
28,II,EQUITY AND LIABILITIES,NaN,NaN,NaN
29,NaN,Equity,NaN,NaN,NaN
30,NaN,(a) Equity share capital,13,585.9,585.9
31,NaN,(b) Other equity,14,"112,920.3","99,239.9"
32,NaN,Total equity,NaN,"113,506.2","99,825.8"
33,NaN,Liabilities,NaN,NaN,NaN
34,NaN,Non-current liabilities,NaN,NaN,NaN
35,NaN,(a) Provisions,16(A),226.4,336.0
36,NaN,(b) Deferred tax liability (net),8,310.0,234.8
37,NaN,Total non-current liabilities,NaN,536.4,570.8
38,NaN,Current liabilities,NaN,NaN,NaN
39,NaN,(a) Financial liabilities,NaN,NaN,NaN
40,NaN,(i) Borrowings,15,"45,198.0","36,538.3"
41,NaN,(ii) Trade payables,17,NaN,NaN
42,NaN,(A) total outstanding dues of micro enterprise...,NaN,328.8,296.6
43,NaN,(B) total outstanding dues of creditors other ...,NaN,"18,085.1","15,995.8"
44,NaN,enterprises,NaN,NaN,NaN
45,NaN,(iii) Other financial liabilities,18,"1,286.9","2,526.5"
46,NaN,(b) Other current liabilities,19,"1,500.7","1,439.2"
47,NaN,(c) Provisions,16(B),965.1,745.4
48,NaN,Total current liabilities,NaN,"67,364.6","57,541.8"
49,NaN,TOTAL EQUITY AND LIABILITIES,NaN,"181,407.2","157,938.4"
50,NaN,Summary of significant accounting policies,2.2,NaN,NaN

## P&L Statement

In [7]:
# open the pdf file
object = pdf.PdfFileReader("APL-Annual-Report-2018-19.pdf")

# get number of pages
NumPages = object.getNumPages()

String1 = "STANDALONE STATEMENT OF PROFIT AND LOSS"

for i in range(0, NumPages):
    PageObj = object.getPage(i)
    Text = PageObj.extractText() 
    # print(Text)
    if  re.search(String1, Text) != None:
        print("This is page " + str(i))
        page=object.getPage(i)
        pdf_writer=pdf.PdfFileWriter()
        pdf_writer.addPage(page)
        output=open('p&l_aurobindo_1819.pdf','wb')
        pdf_writer.write(output)
        output.close()
        df_pl1819=read_pdf('p&l_aurobindo_1819.pdf')
df_pl1819[0]
print(tabulate(df_pl1819[0]))

'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 144
--  ----  --------------------------------------------------------------------------------  ----  -------------  -------------
 0  nan   nan                                                                               Note  nan            nan
 1  nan   nan                                                                               nan   31 March 2019  31 March 2018
 2  I     INCOME                                                                            nan   nan            nan
 3  nan   Revenue from operations                                                           20    122,578.9      103,031.5
 4  nan   Other income                                                                      21    1,992.2        806.5
 5  nan   TOTAL INCOME (I)                                                                  nan   124,571.1      103,838.0
 6  II    EXPENSES                                                                          nan   nan            nan
 7  nan   Cost of materials consumed                                                        22    64,553.0       48,932.7
 8  nan   Purchases of stock-in-trade                                                       nan   142.5          37.2
 9  nan   Changes in inventories of  finished goods, stock-in-trade and work-in-progress    23    (2,898.0)      (3,341.8)
10  nan   Employee benefits expense                                                         24    13,627.7       11,316.4
11  nan   Finance costs                                                                     25    2,308.6        528.9
12  nan   Depreciation and amortisation expense                                             26    4,130.3        3,548.3
13  nan   Other expenses                                                                    27    23,060.8       19,386.9
14  nan   TOTAL EXPENSES (II)                                                               nan   104,924.9      80,408.6
15  III   PROFIT BEFORE TAX (I-II)                                                          nan   19,646.2       23,429.4
16  IV    TAX EXPENSE :                                                                     28    nan            nan
17  nan   Current tax                                                                       nan   4,266.1        5,053.4
18  nan   Tax credit - Minimum Alternate Tax (MAT)                                          nan   (480.5)        (433.2)
19  nan   Deferred tax                                                                      nan   563.3          681.5
20  nan   TOTAL TAX EXPENSE (IV)                                                            nan   4,348.9        5,301.7
21  V     PROFIT FOR THE YEAR (III-IV)                                                      nan   15,297.3       18,127.7
22  VI    OTHER COMPREHENSIVE INCOME (OCI)                                                  nan   nan            nan
23  nan   Items that will not to be reclassified subsequently to profit or loss:            nan   nan            nan
24  nan   (a) Re-measurement of defined benefit liability                                   nan   (21.7)         (34.5)
25  nan   (b) Income-tax relating to items that will not be reclassified to profit or loss  nan   7.6            12.7
26  nan   TOTAL OTHER COMPREHENSIVE INCOME FOR THE YEAR (NET OF TAX) (VI)                   nan   (14.1)         (21.8)
27  VII   TOTAL COMPREHENSIVE INCOME FOR THE YEAR (NET OF TAX) (V+VI)                       nan   15,283.2       18,105.9
28  VIII  EARNINGS PER EQUITY SHARE                                                         29    nan            nan
29  nan   Basic (in `)                                                                      nan   26.11          30.94
30  nan   Diluted (in `)                                                                    nan   26.11          30.94
31  nan   Nominal value per equity share                                                    nan   1.00           1.00
32  nan   Summary of significant accounting policies                                        2.2   nan            nan
--  ----  --------------------------------------------------------------------------------  ----  -------------  -------------

## Cash Flow Statement

In [38]:
# open the pdf file
object = pdf.PdfFileReader("APL-Annual-Report-2018-19.pdf")
# get number of pages
NumPages = object.getNumPages()

String2 = "STANDALONE STATEMENT OF CASH FLOW"

for i in range(0, NumPages):
    PageObj = object.getPage(i)
    Text = PageObj.extractText() 
    # print(Text)
    pdf_writer=pdf.PdfFileWriter()
    if  re.search(String2, Text) != None:
        print("This is page " + str(i))
        page=object.getPage(i)
#         pdf_writer=pdf.PdfFileWriter()
        pdf_writer.addPage(page)
        output=open('cashflow1.pdf','wb')
        pdf_writer.write(output)
    output.close()

This is page 146
This is page 147

# Aurobindo Pharma 16-17

## Balance Sheet

In [16]:
# open the pdf file
object = pdf.PdfFileReader("Annual-Report-2016-17.pdf")

# get number of pages
NumPages = object.getNumPages()

# define keyterms
String = "Balance Sheet as at March 31, 2017"
# String1 = "STANDALONE STATEMENT OF PROFIT AND LOSS"
# String2 = "STANDALONE STATEMENT OF CASH FLOW"
# extract text and do the search
for i in range(0, NumPages):
    PageObj = object.getPage(i)
    Text = PageObj.extractText() 
    # print(Text)
    if  re.search(String, Text) != None:
        print("This is page " + str(i))
        page=object.getPage(i)
        pdf_writer=pdf.PdfFileWriter()
        pdf_writer.addPage(page)
        output=open('balancesheet_aurobindo1617.pdf','wb')
        pdf_writer.write(output)
        output.close()
        df_bl1617=read_pdf('balancesheet_aurobindo1617.pdf')
df_bl1617[0]

PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]
'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 110

Got stderr: Jan 30, 2020 9:23:09 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:09 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:09 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:09 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:10 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:10 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold

'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 115

Got stderr: Jan 30, 2020 9:23:12 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:12 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book

'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 164

Got stderr: Jan 30, 2020 9:23:17 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:17 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:18 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:18 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:18 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:18 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold

'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 167

Got stderr: Jan 30, 2020 9:23:20 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:20 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book

'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 205

Got stderr: Jan 30, 2020 9:23:24 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:24 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:25 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:25 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:25 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:25 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book

'pages' argument isn't specified.Will extract only from page 1 by default.

This is page 222

Got stderr: Jan 30, 2020 9:23:29 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for quotedbl (34) in font ZapfDingbats
Jan 30, 2020 9:23:29 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font Arial-BoldMT for OfficinaSans-Bold
Jan 30, 2020 9:23:29 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font ArialMT for OfficinaSans-Book
Jan 30, 2020 9:23:29 PM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored

       Resolution No.                                         Resolution
0   Ordinary Business                                                NaN
1                  1.  To receive, consider and adopt the Audited Sta...
2                  2.  To receive, consider and adopt the Audited Con...
3                  3.  To confirm the first interim dividend of `1.25...
4                  4.  To appoint a Director in place of Mr. P. Sarat...
5                  5.  To appoint a Director in place of Dr. M. Sivak...
6                  6.  To appoint M/s. B S R & Associates LLP, Charte...
7    Special Business                                                NaN
8                  7.  Re-appointment of Mr. P.V. Ramprasad Reddy, Di...
9                  8.  Appointment of Mr. Rangaswamy Rathakrishnan Iy...
10                 9.  To revise the remuneration of Mr. N. Govindara...

In [28]:
# open the pdf file
object = pdf.PdfFileReader("Annual-Report-2016-17.pdf")

# get number of pages
NumPages = object.getNumPages()

# define keyterms
String = "K. Nithyananda Reddy"
# String1 = "STANDALONE STATEMENT OF PROFIT AND LOSS"
# String2 = "STANDALONE STATEMENT OF CASH FLOW"
# extract text and do the search
for i in range(0, NumPages):
    PageObj = object.getPage(i)
    Text = PageObj.extractText() 
    # print(Text)
    if  re.search(String, Text) != None:
        print("This is page " + str(i))
        page=object.getPage(i)
        pdf_writer=pdf.PdfFileWriter()
        pdf_writer.addPage(page)
        output=open('vicechairmanspeech.pdf','wb')
        pdf_writer.write(output)
        output.close()

This is page 8
This is page 71
This is page 82
This is page 88
This is page 94
This is page 95
This is page 96
This is page 97
This is page 98
This is page 100
This is page 101
This is page 148
This is page 152
This is page 205
This is page 206

In [ ]:
!pip install fitz
# import fitz

# filename = "Annual-Report-2017-18.pdf"
# search_term = "K. Nithyananda Reddy"
# pdf_document = fitz.open(filename)

# for current_page in range(len(pdf_document)):
#     page = pdf_document.loadPage(current_page)
#     if page.searchFor(search_term):
#         print("%s found on page %i" % (search_term, current_page))